version: '3'
services:
  koop:
    build:
      context: .
    ports:
      - "9100:9000"
    hostname: "koop"
    container_name: "koop"
    environment:
      - NODE_ENV=docker
      - MARKLOGIC_HOST=${MARKLOGIC_HOST}
      - MARKLOGIC_PORT=${MARKLOGIC_PORT}
      - ESRI_AUTH_SECRET=${ESRI_AUTH_SECRET}
