title: MarkLogic Koop Provider
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "koopjs/koop-provider-marklogic":
    - "https://github.com/koopjs/koop-provider-marklogic"

enable_copy_code_button: true
